#!/usr/bin/env sh
#
# Bring up the whole stack and seed a project you can connect to.
#
#   ./quickstart/quickstart.sh
#
# Generates .env on first run, starts Postgres, the example host, kraken and the
# admin UI, then imports quickstart/demo-project.json and prints the credentials
# it mints.
#
# Safe to re-run. A second run imports a second demo project rather than
# failing.

set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

ENV_FILE="$ROOT/.env"

say() { printf '%s\n' "$*"; }

# ── Random values ──────────────────────────────────────────────────────────

rand_b64url() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand "$1" | base64 | tr '+/' '-_' | tr -d '=\n'
  else
    dd if=/dev/urandom bs="$1" count=1 2>/dev/null | base64 | tr '+/' '-_' | tr -d '=\n'
  fi
}

rand_b64() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$1" | tr -d '\n'
  else
    dd if=/dev/urandom bs="$1" count=1 2>/dev/null | base64 | tr -d '\n'
  fi
}

if [ ! -f "$ENV_FILE" ]; then
  say "Generating $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by quickstart.sh. Keep it out of version control.

# 32 bytes, base64. Encrypts signing keys at rest, which is what makes browser
# client tokens possible. Losing it makes existing signing keys unreadable.
SIGNING_KEY_ENCRYPTION_KEY=$(rand_b64 32)

# Guards kraken's internal publish endpoint.
KRAKEN_INTERNAL_SECRET=$(rand_b64url 32)

POSTGRES_PASSWORD=$(rand_b64url 24)

# Published ports. Change these if something already holds them.
POSTGRES_PORT=5442
CORE_PORT=3400
KRAKEN_PORT=8410
KRAKEN_MQTT_PORT=18843
UI_PORT=3401
EOF
  chmod 600 "$ENV_FILE"
else
  say "Using existing $ENV_FILE"
fi

# shellcheck disable=SC1090
. "$ENV_FILE"

CORE_URL="http://localhost:${CORE_PORT:-3400}"
KRAKEN_WS="ws://localhost:${KRAKEN_PORT:-8410}/ws"
UI_URL="http://localhost:${UI_PORT:-3401}"

say ""
say "Building and starting the stack. The first run compiles kraken from"
say "source, which takes a few minutes."
say ""

# --wait blocks until every service with a healthcheck reports healthy and
# fails if one does not, so a broken stack stops here rather than surfacing as
# a confusing connection error later.
docker compose up -d --build --wait

say ""
say "Seeding the demo project"

CREDS="$ROOT/quickstart/credentials.json"

# No Authorization header: the example host authenticates nobody.
HTTP_CODE=$(curl -sS -o "$CREDS" -w '%{http_code}' \
  -X POST "$CORE_URL/v1/projects/import" \
  -H 'Content-Type: application/json' \
  --data-binary @"$ROOT/quickstart/demo-project.json")

if [ "$HTTP_CODE" != "201" ]; then
  say ""
  say "Import failed with HTTP $HTTP_CODE:"
  cat "$CREDS"
  say ""
  rm -f "$CREDS"
  exit 1
fi

chmod 600 "$CREDS"

say ""
say "Done."
say ""
say "  Admin UI   $UI_URL"
say "  Host API   $CORE_URL      (docs at $CORE_URL/swagger)"
say "  Broker     $KRAKEN_WS"
say ""
say "Access tokens for the demo actors are in quickstart/credentials.json."
say "They are shown once: core stores only their hashes."
say ""
say "Nothing here asks for a credential. The host authenticates nobody, and"
say "every port is bound to 127.0.0.1 for exactly that reason."
say ""
say "Stop with:    docker compose down"
say "Wipe data:    docker compose down -v"
